
spring:
  profiles:
    active: local
---
spring:
  profiles: local
  datasource:
    hikari:
    url: jdbc:h2:tcp://localhost/~/test
    username: sa
    password: 1234
    driver-class-name: org.h2.Driver